### ISSUE TITLE
no vgg19.npy

### ISSUE THREAD

**Issue by TracesChen** [cl199443/Deep-Semantic-Feature-Matching#2]
Hi @cl199443 
please helping me , thanks!
Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "/home/ubuntu/Deep-Semantic-Feature-Matching-master/vgg19.py", line 20, in __init__
    self.data_dict = np.load(vgg19_npy_path, encoding='latin1').item()
  File "/home/ubuntu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/ubuntu/Deep-Semantic-Feature-Matching-master/vgg19.npy'
/home/ubuntu/Deep-Semantic-Feature-Matching-master/vgg19.npy

**Comment by cl199443** [comment]
hello, this file can be found here (https://github.com/machrisaa/tensorflow-vgg) and it's just a pre-trained model parameter file.

**Comment by TracesChen** [comment]
thank you very much 




------------------ 原始邮件 ------------------
发件人: "Lang Chen"<notifications@github.com>;
发送时间: 2019年6月16日(星期天) 晚上8:45
收件人: "cl199443/Deep-Semantic-Feature-Matching"<Deep-Semantic-Feature-Matching@noreply.github.com>;
抄送: "Dream"<1216159885@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cl199443/Deep-Semantic-Feature-Matching] no vgg19.npy (#2)




hello, this file can be found here (https://github.com/machrisaa/tensorflow-vgg) and it's just a pre-trained model parameter file.
